version: "3"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - ./server:/server
    networks:
      - my-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-password
      - MYSQL_ROOT_PASSWORD=my-secret-password
      - MYSQL_DATABASE=WibuStore
      - DATA_ANALYSIS_SERVER=data-analysis-server
      - DATA_ANALYSIS_SERVER_PORT=80
    depends_on:
      - mysql

  data-analysis-server:
    build:
      context: ./data-analysis-server
      dockerfile: Dockerfile
    volumes:
      - ./data-analysis-server:/data-analysis-server
    networks:
      - my-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-password
      - MYSQL_DATABASE=WibuStore
    depends_on:
      - mysql
      - server

  search-engine:
    build:
      context: ./search-engine
      dockerfile: Dockerfile
    volumes:
      - ./search-engine:/search-engine
    networks:
      - my-network
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-password
      - MYSQL_DATABASE=WibuStore

  redis:
    image: redis
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql-server
      dockerfile: Dockerfile
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-password
      - MYSQL_DATABASE=WibuStore
networks:
  my-network:
    driver: bridge